# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RemoteSensingToolkit
                                 A QGIS plugin
 This plugin computes biophysical indices
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-12
        copyright            : (C) 2023 by F.E. Ezzaher; N. Ben Achhab; H. Naciri; N. Raissouni
        email                : RST.QGIS@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RemoteSensingToolkit class from file RemoteSensingToolkit.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .remote_sensing_toolkit import RemoteSensingToolkit
    return RemoteSensingToolkit(iface)
